{% extends "setuptools.yaml" %}

{% block package %}
package:
  name: {{data.get('name').lower()}}
  version: {{data.get('version')}}
{% endblock %}

{% block build %}
build:
  script:  # [not win]
      - export MACOSX_DEPLOYMENT_TARGET=""  # [osx]
      - python setup.py build  # [not win]
      - python setup.py install  # [not win]
  script:  # [win]
      - "%PYTHON%" setup.py build  # [win]
      - "%PYTHON%" setup.py install  # [win]
      - if errorlevel 1 exit 1  # [win]
source:
  path: ..
{% endblock %}

{% block requirements %}
requirements:
  build:
    - python
    - cmake
    - setuptools
    - jinja2
    - libnetcdf
    {% for req in data.get('install_requires', []) -%}
    - {{req|lower}}
    {% endfor %}

  run:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{req|lower}}
    {% endfor %}
{% endblock %}

{% block about %}
about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  summary: {{data.get('summary')}}
{% endblock %}
