language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export EXTRA_WORK=true
    else
        export EXTRA_WORK=false
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        export CC=gcc-4.9
        export CXX=g++-4.9
    fi
  - pip install codecov

script:
  - cd $TRAVIS_BUILD_DIR
  - pip install -r dev-requirements.txt
  - tox
  - ./scripts/check-used-functions.py
  - ./scripts/build-docs.sh
  - |
    if ${EXTRA_WORK}; then
        pip install -e .
        coverage run -m unittest discover -s tests -p "*.py"
        coverage report
        coverage xml --include="${TRAVIS_BUILD_DIR}/chemfiles/*" -o coverage.xml
        codecov --file coverage.xml
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        branch: master
        python: "3.5"
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        tags: true
        python: "3.5"
