language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export EXTRA_WORK=true
    else
        export EXTRA_WORK=false
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        export CC=gcc-4.9
        export CXX=g++-4.9
    fi
  - |
    if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        pip install enum34
    fi
  - pip install numpy
  - pip install codecov

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake -DCHFL_PY_CODE_COVERAGE=ON ..
  - make
  - ctest --output-on-error
  - cd $TRAVIS_BUILD_DIR
  - ./scripts/build-docs.sh
  - |
    if ${EXTRA_WORK}; then
        cd ${TRAVIS_BUILD_DIR}/tests
        coverage report
        coverage xml --include="${TRAVIS_BUILD_DIR}/build/src/*" -o coverage.xml
        codecov --file coverage.xml
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        branch: master
        python: "3.5"
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        tags: true
        python: "3.5"
