language: python
sudo: false
python:
  - "2.7"
  - "3.5"
os:
  - linux
env:
  global:
    secure: vemv2pi+y10L/3QkiDTdgbsug2Qv97OUiMjyRw9pYIjDoNhws1jzuKMFJt1YvUNZcROUA1hEkDYDDCmGTXAo7zr+pk+ru9e8h6q9LH+uPZWKgWHUzEyFlLB3wve3fCzeTIqvvSC+87bxYhJg53TrrCyRXBu3jnHoqJKr2RhWwOQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - libnetcdf-dev
    - cmake

before_install:
  - |
    if test "${TRAVIS_OS_NAME}" == "linux"; then
        export CC=gcc-4.9
        export CXX=g++-4.9
    fi
  - |
    if test "${TRAVIS_PYTHON_VERSION}" == "2.7"; then
        pip install enum34
    fi
  - pip install numpy
  - pip install codecov

install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install
script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - coverage run -m unittest discover

after_success:
  - coverage report
  - |
    if test "${TRAVIS_OS_NAME}" == "linux" && test "${TRAVIS_PYTHON_VERSION}" == "2.7"; then
        codecov
    fi

deploy:
  provider: script
  script: bash ${TRAVIS_BUILD_DIR}/recipe/deploy.sh
  on:
    tags: true
