version: "{build}"

environment:
  matrix:
    - generator: Visual Studio 14 2015 Win64
      ARCH: x64
    - generator: Visual Studio 14 2015
      ARCH: x86
    - generator: MinGW Makefiles
      CXX_PATH: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin'
      ARCH: x64
    - generator: MinGW Makefiles
      CXX_PATH: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin'
      ARCH: x86

configuration:
  - Release

notifications:
  - provider: Email
    to: [luthaf@luthaf.fr]
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - git submodule update --init
  - ps: .\scripts\setup-appveyor.ps1

build_script:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - python setup.py develop -- %CMAKE_ARGUMENTS% -- %BUILD_ARGUMENTS%

test_script:
  - python -m unittest discover -s tests -p "*.py"
