name: Test

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"]
        include:
          - os: windows-2019
            python-version: "3.8"
          - os: macos-10.15
            python-version: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: run tests (Unix)
        if: matrix.os != 'windows-2019'
        run: tox
      - name: run tests (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          tox
        shell: cmd
      - name: run extra checks
        run: |
          ./scripts/check-used-functions.py
      - uses: codecov/codecov-action@v1
        with:
          file: .tox/coverage.xml
